services:

  db:
    image: mariadb:latest
    container_name: 'digitalbusinesscard-db'
    restart: always
    volumes:
      - ./.docker/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - digitalbusinesscard_network
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-p$MYSQL_ROOT_PASSWORD", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: 'digitalbusinesscard-pma'
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 512M
      MAX_EXECUTION_TIME: 3000
    ports:
      - "8080:80"
    networks:
      - digitalbusinesscard_network
    depends_on:
      db:
        condition: service_healthy

  php:
    image: php:8.3-fpm
    container_name: 'digitalbusinesscard-php'
    restart: always
    working_dir: /var/www/
    volumes:
      - ./app:/var/www/html
    networks:
      - digitalbusinesscard_network

  nginx:
    image: nginx:latest
    container_name: 'digitalbusinesscard-nginx'
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - digitalbusinesscard_network

networks:
  digitalbusinesscard_network:
    external: true